#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    arr = []

    for _ in range(6):
        arr.append(list(map(int, input().rstrip().split())))
    sum1=[]
    h=0
    msum=-63
    
    for i in range(0,4):
        for j in range(0,4):
            t=0
            t = arr[i][j] + arr[i][j+1] + arr[i][j+2] + arr[i+1][j+1] + arr[i+2][j] + arr[i+2][j+1] + arr[i+2][j+2]
            #if(t>msum):
            #    msum=t
            #else:
            #    t=0
            sum1.append(t)
            
    print(max(sum1))
    #print(msum)
